import { Platform, StyleSheet } from 'react-native';

import { RITUAL_COLORS } from '../../../shared/constants';

export const createStyles = () => {
  return StyleSheet.create({
    modalOverlay: { flex: 1, justifyContent: 'flex-end' },
    backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: RITUAL_COLORS.overlay.backdrop },
    modalContent: {
      backgroundColor: RITUAL_COLORS.background.primary,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      height: '85%',
      maxHeight: '90%',
      flexDirection: 'column',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 16,
      flexShrink: 0,
    },
    title: {
      fontSize: 18,
      fontWeight: '600',
      color: RITUAL_COLORS.text.primary,
      flex: 1,
      textAlign: 'center',
    },
    closeButton: {
      padding: 4,
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    deleteButton: {
      padding: 4,
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollView: { flex: 1, flexGrow: 1 },
    scrollContent: {
      paddingHorizontal: 20,
      paddingVertical: 20,
      paddingBottom: 40,
      flexGrow: 1,
    },
    inputSection: { marginBottom: 24 },
    label: {
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      color: RITUAL_COLORS.text.secondary,
    },
    input: {
      height: 50,
      borderRadius: 12,
      paddingHorizontal: 16,
      fontSize: 16,
      borderWidth: 1,
      color: RITUAL_COLORS.text.primary,
      backgroundColor: RITUAL_COLORS.background.input,
      borderColor: RITUAL_COLORS.border.input,
    },
    pinRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    timeRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    timeInput: { flex: 1 },
    timeSeparator: { fontSize: 16, color: RITUAL_COLORS.text.secondary },
    dropdown: {
      height: 50,
      borderRadius: 12,
      paddingHorizontal: 16,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: RITUAL_COLORS.background.input,
      borderColor: RITUAL_COLORS.border.input,
    },
    dropdownText: { fontSize: 16, color: RITUAL_COLORS.text.primary, flex: 1 },
    dropdownPlaceholder: { color: RITUAL_COLORS.text.tertiary },
    dropdownList: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      overflow: 'hidden',
      backgroundColor: RITUAL_COLORS.background.secondary,
      borderColor: RITUAL_COLORS.border.input,
    },
    dropdownItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: RITUAL_COLORS.border.divider,
    },
    dropdownItemText: { fontSize: 16, color: RITUAL_COLORS.text.primary, marginLeft: 12 },
    repeatOnHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
    everyDayLink: { fontSize: 14, color: RITUAL_COLORS.accent.primary, fontWeight: '500' },
    daysContainer: { flexDirection: 'row', gap: 8 },
    dayButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: RITUAL_COLORS.background.secondary,
      borderWidth: 1,
      borderColor: RITUAL_COLORS.border.input,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayButtonSelected: {
      borderColor: RITUAL_COLORS.accent.primary,
      backgroundColor: RITUAL_COLORS.accent.primary,
    },
    dayButtonText: { fontSize: 14, fontWeight: '600', color: RITUAL_COLORS.text.primary },
    dayButtonTextSelected: { color: RITUAL_COLORS.text.primary },
    actions: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: Platform.OS === 'ios' ? 34 : 20,
      flexShrink: 0,
    },
    saveButton: {
      height: 50,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
      gap: 8,
      backgroundColor: RITUAL_COLORS.accent.primary,
    },
    saveButtonDisabled: { opacity: 0.45 },
    saveButtonActive: { opacity: 1 },
    saveButtonText: { color: RITUAL_COLORS.text.primary, fontSize: 16, fontWeight: '600' },
    cancelButton: { alignItems: 'center', justifyContent: 'center', paddingVertical: 8 },
    cancelButtonText: { fontSize: 16, color: RITUAL_COLORS.text.tertiary, fontWeight: '500' },
  });
};
