import { Dimensions, StyleSheet } from 'react-native';

import { RITUAL_COLORS } from '../../../shared/constants';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const PICKER_SHADOW = {
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 } as const,
  shadowOpacity: 0.3,
  shadowRadius: 8,
};

export const createStyles = () => {
  return StyleSheet.create({
    container: {
      backgroundColor: 'transparent',
      paddingTop: 0,
      paddingBottom: 0,
      borderBottomWidth: 1,
      borderBottomColor: RITUAL_COLORS.border.divider,
      marginBottom: 8,
    },
    calendarWrapper: {
      height: 100,
      marginTop: -4,
      marginBottom: 0,
      minHeight: 100,
      backgroundColor: 'transparent',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 24,
      paddingLeft: 24,
      paddingBottom: 0,
      paddingTop: 2,
      position: 'relative',
    },
    viewAllButton: { paddingVertical: 6, paddingHorizontal: 0 },
    viewAllText: {
      fontSize: 13,
      fontWeight: '600',
      color: RITUAL_COLORS.accent.primary,
    },
    thisWeekTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: RITUAL_COLORS.text.primary,
      textTransform: 'uppercase',
      opacity: 0.9,
    },
    calendarViewOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      backgroundColor: RITUAL_COLORS.overlay.backdrop,
      zIndex: 1000,
      paddingHorizontal: 20,
      paddingTop: 50,
      paddingBottom: 24,
    },
    calendarViewContainer: {
      backgroundColor: RITUAL_COLORS.background.secondary,
      borderRadius: 12,
      padding: 16,
      maxHeight: '90%',
      ...PICKER_SHADOW,
    },
    datePickerModal: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: RITUAL_COLORS.overlay.backdrop,
    },
    datePickerModalContent: {
      backgroundColor: RITUAL_COLORS.background.card,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      padding: 16,
      paddingBottom: 32,
    },
    datePickerDoneButton: {
      marginTop: 16,
      paddingVertical: 14,
      alignItems: 'center',
      backgroundColor: RITUAL_COLORS.accent.primary,
      borderRadius: 12,
    },
    datePickerDoneText: {
      fontSize: 16,
      fontWeight: '600',
      color: RITUAL_COLORS.text.primary,
    },
    dateSelectorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 18,
    },
    dateSelector: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 4, paddingHorizontal: 0 },
    dateSelectorText: {
      fontSize: 13,
      fontWeight: '500',
      color: RITUAL_COLORS.text.secondary,
      flexShrink: 0,
    },
    dateSelectorToday: { backgroundColor: RITUAL_COLORS.accent.primary },
    dateSelectorTextToday: { color: RITUAL_COLORS.text.primary },
    chevron: { fontSize: 12, color: RITUAL_COLORS.text.secondary },
    pickerContainer: {
      position: 'absolute',
      top: 50,
      left: 20,
      right: 20,
      backgroundColor: RITUAL_COLORS.background.secondary,
      borderRadius: 12,
      padding: 16,
      zIndex: 1000,
      elevation: 8,
      ...PICKER_SHADOW,
      maxHeight: 300,
    },
    pickerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: RITUAL_COLORS.border.divider,
    },
    pickerTitle: {
      fontSize: 12,
      fontWeight: '600',
      color: RITUAL_COLORS.text.secondary,
      textTransform: 'uppercase',
    },
    pickerClose: {
      fontSize: 16,
      color: RITUAL_COLORS.text.secondary,
      fontWeight: 'bold',
    },
    pickerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    pickerItem: {
      width: '30%',
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 8,
      backgroundColor: RITUAL_COLORS.background.primary,
      alignItems: 'center',
    },
    pickerItemSelected: { backgroundColor: RITUAL_COLORS.accent.primary },
    pickerItemText: { fontSize: 14, color: RITUAL_COLORS.text.primary },
    pickerItemTextSelected: { color: RITUAL_COLORS.text.primary, fontWeight: '600' },
    yearPickerContainer: {
      position: 'absolute',
      top: 50,
      left: 20,
      right: 20,
      backgroundColor: RITUAL_COLORS.background.secondary,
      borderRadius: 12,
      padding: 16,
      zIndex: 1000,
      elevation: 8,
      ...PICKER_SHADOW,
      maxHeight: 400,
    },
    yearPickerListScroll: { flex: 1, maxHeight: 340 },
    yearPickerList: { paddingBottom: 16 },
    yearPickerItem: {
      height: 48,
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 8,
      backgroundColor: RITUAL_COLORS.background.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 4,
      marginVertical: 2,
    },
    yearPickerItemSelected: { backgroundColor: RITUAL_COLORS.accent.primary },
    yearPickerItemText: { fontSize: 14, color: RITUAL_COLORS.text.primary },
    yearPickerItemTextSelected: { color: RITUAL_COLORS.text.primary, fontWeight: '600' },
    weekContainer: {
      flexDirection: 'row',
      width: SCREEN_WIDTH,
      paddingHorizontal: 8,
    },
    dayContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 6,
      marginHorizontal: 2,
    },
    dayName: {
      fontSize: 11,
      fontWeight: '500',
      color: RITUAL_COLORS.text.secondary,
      textTransform: 'uppercase',
      marginBottom: 6,
    },
    dayNameToday: { color: RITUAL_COLORS.accent.primary, fontWeight: '600' },
    dayNameSelectedMuted: { color: RITUAL_COLORS.accent.primary, fontWeight: '600' },
    dayCircleWrapper: {
      width: 28,
      height: 28,
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayCircleSvg: {
      position: 'absolute',
      left: 0,
      top: 0,
      width: 28,
      height: 28,
    },
    dayCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: 0,
    },
    dayCircleSelected: { backgroundColor: 'transparent' },
    dayNumber: {
      fontSize: 14,
      fontWeight: '600',
      color: RITUAL_COLORS.text.secondary,
      textAlign: 'center',
    },
    dayNumberSelected: { color: RITUAL_COLORS.text.primary, fontWeight: '600' },
    todayDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: RITUAL_COLORS.accent.primary,
      marginTop: 4,
    },
  });
};
